-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) as 'TOTAL_SALES'
FROM BOOK B
    INNER JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
    INNER JOIN BOOK_SALES BS 
            ON B.BOOK_ID = BS.BOOK_ID
            AND BS.SALES_DATE >= '2022-01-01' 
            AND BS.SALES_DATE < '2022-02-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC