SELECT ID, IFNULL(CNT, 0) as 'CHILD_COUNT'
FROM ECOLI_DATA A
LEFT JOIN 
    (
        SELECT PARENT_ID, COUNT(ID) as 'CNT'
        FROM ECOLI_DATA
        GROUP BY PARENT_ID
    ) B
ON A.ID = B.PARENT_ID
ORDER BY ID;