SELECT 
    A.CAR_ID, 
    A.CAR_TYPE,
    ROUND(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) as 'FEE'
FROM CAR_RENTAL_COMPANY_CAR A
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%'
    ) B ON A.CAR_TYPE = B.CAR_TYPE
WHERE CAR_ID NOT IN (
                        SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01'
                    )
    AND A.CAR_TYPE IN ('세단', 'SUV')
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
    
    
    
    


