-- 코드를 입력하세요

SELECT 
    A.WRITER_ID as 'USER_ID', 
    B.NICKNAME as 'NICKNAME', 
    CONCAT(B.CITY, ' ', B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8)) AS '전화번호'
FROM (
        SELECT WRITER_ID
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
            HAVING COUNT(WRITER_ID) >= 3
) A
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
ORDER BY A.WRITER_ID DESC;

# SELECT *
# FROM USED_GOODS_BOARD

