# -- 코드를 입력하세요
# SELECT *
# FROM REST_INFO
# WHERE ADDRESS LIKE '서울%'



SELECT RR.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) as 'SCORE'
FROM REST_REVIEW RR
    INNER JOIN REST_INFO RI ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RR.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC