-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(AMOUNT) * FP.PRICE as 'TOTAL_SALES'
# SELECT *
FROM FOOD_ORDER FO
    INNER JOIN FOOD_PRODUCT FP ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE >= "2022-05-01" AND FO.PRODUCE_DATE < "2022-06-01"
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID


# SELECT *
# FROM FOOD_ORDER
# ORDER BY 


