-- 코드를 입력하세요

SELECT 
    A.WRITER_ID as 'USER_ID', 
    B.NICKNAME as 'NICKNAME', 
    A.SUM_PRICE as 'TOTAL_SALES'
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS 'SUM_PRICE'
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000
) A
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
ORDER BY TOTAL_SALES;