
SELECT YEAR(A.DIFFERENTIATION_DATE) as 'YEAR', (B.maxSize - A.SIZE_OF_COLONY) as 'YEAR_DEV', A.ID
FROM ECOLI_DATA A
    INNER JOIN (SELECT YEAR(DIFFERENTIATION_DATE) as 'YEAR', MAX(SIZE_OF_COLONY) as 'maxSize'
                FROM ECOLI_DATA
                GROUP BY YEAR(DIFFERENTIATION_DATE)) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC





















# -- 코드를 작성해주세요
# SELECT year(A.DIFFERENTIATION_DATE) as 'YEAR', (B.MAX_COLONY - A.SIZE_OF_COLONY) as 'YEAR_DEV', A.ID as 'ID'
# FROM ECOLI_DATA A
# LEFT JOIN (SELECT year(DIFFERENTIATION_DATE) as 'YEAR', max(SIZE_OF_COLONY) as 'MAX_COLONY'
#             FROM ECOLI_DATA
#             GROUP BY year(DIFFERENTIATION_DATE)) B
# ON year(A.DIFFERENTIATION_DATE) = B.YEAR
# ORDER BY YEAR, YEAR_DEV;