-- 코드를 작성해주세요
SELECT year(A.DIFFERENTIATION_DATE) as 'YEAR', (B.MAX_COLONY - A.SIZE_OF_COLONY) as 'YEAR_DEV', A.ID as 'ID'
FROM ECOLI_DATA A, (SELECT year(DIFFERENTIATION_DATE) as 'YEAR', max(SIZE_OF_COLONY) as 'MAX_COLONY'
                    FROM ECOLI_DATA
                    GROUP BY year(DIFFERENTIATION_DATE)) B
WHERE year(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;