-- 코드를 입력하세요

SELECT A.CAR_ID
FROM (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(START_DATE) = 10
        GROUP BY CAR_ID
     ) A
LEFT JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC;
