-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM (SELECT CATEGORY, PRODUCT_NAME, PRICE, 
            ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) as 'RANK'
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) A
WHERE A.RANK = 1
GROUP BY A.CATEGORY
ORDER BY A.PRICE DESC